<?php
/**
 * File: RewriteDataInterface.php
 *
 * @author Maciej Sławik <maciej.slawik@lizardmedia.pl>
 * @copyright Copyright (C) 2018 Lizard Media (http://lizardmedia.pl)
 */

namespace LizardMedia\GoogleAnalyticsVerifier\Api\Rewrite;

/**
 * Interface RewriteDataInterface
 * @package LizardMedia\GoogleAnalyticsVerifier\Api\Rewrite
 */
interface RewriteDataInterface
{
    /**
     * @var array
     */
    public const GENERATED_REWRITE_DATA = [
        'redirect_type' => 0,
        'entity_type' => 'custom',
        'is_autogenerated' => '0',
    ];
}
